# Generated by Django 3.0.7 on 2020-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200627_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(null=True, verbose_name='Data do Evento'),
        ),
    ]
