# Generated by Django 3.0.7 on 2020-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200627_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_criacao',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Evento'),
        ),
    ]
