# Generated by Django 3.0.8 on 2020-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200629_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(null=True, verbose_name='Data do Evento'),
        ),
    ]
