# Generated by Django 3.0.7 on 2020-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200628_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_criacao',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
