# Generated by Django 3.0.7 on 2020-06-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200628_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
